name: swiss_knife
description: Dart Useful Tools - collections, math, date, uri, json, events, resources, regexp, etc...
version: 3.0.2
homepage: https://github.com/gmpassos/swiss_knife

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  resource_portable: ^3.0.0
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  #test_coverage: ^0.4.3

#dependency_overrides:
#  resource_portable:
#    path: ../resource_portable

